security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:     .*
            form_login:
                provider:      fos_userbundle
                login_path:     /backend/login
                use_forward:    false
                check_path:     /backend/login_check
                failure_path:  null
            logout:
                path: /backend/logout
            anonymous:    ~
    access_control:
        - { path: ^/backend/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /backend/, role: ROLE_USER } 
        - { path: /.*, roles: IS_AUTHENTICATED_ANONYMOUSLY}
